/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContainerEditFrame.java
 *
 * Created on Mar 9, 2011, 2:29:40 PM
 */

package org.clothocad.tool.batterboard;

/**
 *
 * @author anna
 */
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.clothocore.api.data.*;
import org.clothocore.api.core.Collector;
import org.clothocore.api.data.Sample.SampleType;

public class ContainerEditFrame extends javax.swing.JFrame {

    /** Creates new form ContainerEditFrame */
    public ContainerEditFrame(Plate plate,Container myC)
    {
        this();
        this.myPlate = plate;
        this.selectedContainer = myC;
        populateContainer();
        if (!(this.jCheckBoxGelSample.isSelected()))
        {
            this.jTextFieldEnzyme1.setEditable(false);
            this.jTextFieldEnzyme2.setEditable(false);
        }

        this.jCheckBoxCharData.setEnabled(false);
    }
    public ContainerEditFrame() {
        //initComponents();
        this.myInitiate();
        
        //populate plasmid dropdown
        Iterator i = plasmidList.iterator();
        while (i.hasNext()){
            this.jComboBoxPlasmid.addItem(i.next());    
        }
        
        //populate strain dropdown
        i =strainList.iterator();
        while (i.hasNext()) {
            this.jComboBoxStrain.addItem(i.next());
            
        }
        //populate sample type dropdown
        this.sampleTypeBox.addItem(SampleType.PLASMID_SAMPLE);
        this.sampleTypeBox.addItem(SampleType.STRAIN_SAMPLE);
        this.sampleTypeBox.addItem(SampleType.OLIGO_SAMPLE);

       
    }

    // if selected container already contains a sample, retrieve the properties of the sample
    // and populate the corresponding fields.
    private void populateContainer()
    {
        this.containerName.setText(this.selectedContainer.getName());
        this.barcode.setText(this.selectedContainer.getBarcode());
        PlasmidSample pls =  (PlasmidSample)this.selectedContainer.getSample();
        if (pls!=null)
        {
            this.updateSample = true;
            this.sampleName.setText(""+pls.getName());
            this.concentrationText.setText(""+pls.getConcentration());
            this.qualityText.setText(""+pls.getQuality());
            this.volumeText.setText(""+pls.getVolume());

            //get search tags if a gel-sample or frozen-stock and turn the appropriate
            //check boxes on

            ArrayList<String> tags = pls.getSearchTags();
            for (String s : tags)
            {
                if (s.equals("gel-sample"))
                {
                    this.jCheckBoxGelSample.setSelected(true);
                    for (String e : tags)
                    {
                        if (e.startsWith("enzyme1"))
                        {
                            String enzyme1 = e.substring(8);
                            this.jTextFieldEnzyme1.setText(""+enzyme1);
                        }
                        else if(e.startsWith("enzyme2"))
                        {
                            String enzyme2 = e.substring(8);
                            this.jTextFieldEnzyme2.setText(""+enzyme2);
                        }
                    }
                }

                if (s.equals("frozen-stock"))
                {
                    this.jCheckBoxisFrozenStock.setSelected(true);
                }
            }

        }
    }

//private variables;
    /* this is set true when there already IS a sample inside the container,
     * and the user simply wishes to change its properties.
     */
    private boolean updateSample = false;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        containerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sampleName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPlasmid = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxStrain = new javax.swing.JComboBox();
        sampleTypeBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        volumeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        concentrationText = new javax.swing.JTextField();
        jCheckBoxGelSample = new javax.swing.JCheckBox();
        jTextFieldEnzyme1 = new javax.swing.JTextField();
        jTextFieldEnzyme2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        qualityText = new javax.swing.JTextField();
        jCheckBoxisFrozenStock = new javax.swing.JCheckBox();
        jButtonCharData = new javax.swing.JButton();
        jCheckBoxCharData = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel2.text")); // NOI18N

        containerName.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.containerName.text")); // NOI18N
        containerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containerNameActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel3.text")); // NOI18N

        barcode.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.barcode.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel7.text")); // NOI18N

        sampleName.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.sampleName.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel10.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel11.text")); // NOI18N

        volumeText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.volumeText.text")); // NOI18N
        volumeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextActionPerformed(evt);
            }
        });

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel4.text")); // NOI18N

        concentrationText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.concentrationText.text")); // NOI18N
        concentrationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concentrationTextActionPerformed(evt);
            }
        });

        jCheckBoxGelSample.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxGelSample.text")); // NOI18N
        jCheckBoxGelSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGelSampleActionPerformed(evt);
            }
        });

        jTextFieldEnzyme1.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jTextFieldEnzyme1.text")); // NOI18N

        jTextFieldEnzyme2.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jTextFieldEnzyme2.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel5.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel12.text")); // NOI18N

        save.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.save.text")); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.cancel.text")); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel13.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel13.text")); // NOI18N

        qualityText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.qualityText.text")); // NOI18N

        jCheckBoxisFrozenStock.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxisFrozenStock.text")); // NOI18N
        jCheckBoxisFrozenStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxisFrozenStockActionPerformed(evt);
            }
        });

        jButtonCharData.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jButtonCharData.text")); // NOI18N
        jButtonCharData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCharDataActionPerformed(evt);
            }
        });

        jCheckBoxCharData.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxCharData.text")); // NOI18N
        jCheckBoxCharData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCharDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barcode)
                            .addComponent(containerName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sampleTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(volumeText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(concentrationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qualityText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxStrain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlasmid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnzyme1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEnzyme2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(cancel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCharData))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sampleName))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxCharData)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxGelSample)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jCheckBoxisFrozenStock)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(containerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sampleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCharData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sampleTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(qualityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(concentrationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxPlasmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxStrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGelSample)
                    .addComponent(jCheckBoxisFrozenStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnzyme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEnzyme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel)
                    .addComponent(jButtonCharData))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitiate()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        containerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sampleName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPlasmid = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxStrain = new javax.swing.JComboBox();
        sampleTypeBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        volumeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        concentrationText = new javax.swing.JTextField();
        jCheckBoxGelSample = new javax.swing.JCheckBox();
        jTextFieldEnzyme1 = new javax.swing.JTextField();
        jTextFieldEnzyme2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        qualityText = new javax.swing.JTextField();
        jCheckBoxisFrozenStock = new javax.swing.JCheckBox();
        jButtonCharData = new javax.swing.JButton();
        jCheckBoxCharData = new javax.swing.JCheckBox();

       // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel2.text")); // NOI18N

        containerName.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.containerName.text")); // NOI18N
        containerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containerNameActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel3.text")); // NOI18N

        barcode.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.barcode.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel7.text")); // NOI18N

        sampleName.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.sampleName.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel10.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel11.text")); // NOI18N

        volumeText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.volumeText.text")); // NOI18N
        volumeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextActionPerformed(evt);
            }
        });

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel4.text")); // NOI18N

        concentrationText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.concentrationText.text")); // NOI18N
        concentrationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concentrationTextActionPerformed(evt);
            }
        });

        jCheckBoxGelSample.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxGelSample.text")); // NOI18N
        jCheckBoxGelSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGelSampleActionPerformed(evt);
            }
        });

        jTextFieldEnzyme1.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jTextFieldEnzyme1.text")); // NOI18N

        jTextFieldEnzyme2.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jTextFieldEnzyme2.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel5.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel12.text")); // NOI18N

        save.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.save.text")); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.cancel.text")); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel13.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jLabel13.text")); // NOI18N

        qualityText.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.qualityText.text")); // NOI18N

        jCheckBoxisFrozenStock.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxisFrozenStock.text")); // NOI18N
        jCheckBoxisFrozenStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxisFrozenStockActionPerformed(evt);
            }
        });

        jButtonCharData.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jButtonCharData.text")); // NOI18N
        jButtonCharData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCharDataActionPerformed(evt);
            }
        });

        jCheckBoxCharData.setText(org.openide.util.NbBundle.getMessage(ContainerEditFrame.class, "ContainerEditFrame.jCheckBoxCharData.text")); // NOI18N
        jCheckBoxCharData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCharDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barcode)
                            .addComponent(containerName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sampleTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(volumeText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(concentrationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qualityText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxStrain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlasmid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnzyme1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEnzyme2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(cancel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCharData))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sampleName))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxCharData)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxGelSample)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jCheckBoxisFrozenStock)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(containerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sampleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCharData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sampleTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(qualityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(concentrationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxPlasmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxStrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGelSample)
                    .addComponent(jCheckBoxisFrozenStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnzyme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEnzyme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel)
                    .addComponent(jButtonCharData))
                .addContainerGap())
        );

        pack();
    }
    private void containerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_containerNameActionPerformed

    private void volumeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeTextActionPerformed

    private void concentrationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concentrationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concentrationTextActionPerformed

    private void jCheckBoxGelSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGelSampleActionPerformed
        // TODO add your handling code here:
        if (this.jCheckBoxGelSample.isSelected())
        {
            this.jTextFieldEnzyme1.setEditable(true);
            this.jTextFieldEnzyme2.setEditable(true);
        }
        else {
            this.jTextFieldEnzyme1.setText(null);
            this.jTextFieldEnzyme2.setText(null);
            this.jTextFieldEnzyme1.setEditable(false);
            this.jTextFieldEnzyme2.setEditable(false);


        }
    }//GEN-LAST:event_jCheckBoxGelSampleActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int row=0; int col=2;
        Container container;
        double vol =0.0, conc = 0.0;
        short quality = 0;
        if (this.selectedContainer!=null)
            container =this.selectedContainer;
        else
            container = myPlate.getContainerAt(row, col);
        try
        {
         vol =Double.parseDouble(this.volumeText.getText());
         conc = Double.parseDouble(this.concentrationText.getText());
         quality =(short)Integer.parseInt(this.qualityText.getText());
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage()+"\nMake sure you Fill in Vol, Conc and Quality!");
        }
        Person person = myPlate.getAuthor();
        //based on type of sample chosen i.e plasmid sample,
        // strain sample and oligo-sample create the corresponding type of sample
        if (this.sampleTypeBox.getSelectedItem()==SampleType.PLASMID_SAMPLE)
        {
            ObjLink pl =(ObjLink)this.jComboBoxPlasmid.getSelectedItem();
            Plasmid myPlasmid=Collector.getPlasmid(pl.uuid);
            ObjLink sl = (ObjLink)this.jComboBoxStrain.getSelectedItem();
            Strain myStrain = Collector.getStrain(sl.uuid);
            PlasmidSample pls =  (PlasmidSample)this.selectedContainer.getSample();
            if (pls==null)
                 pls =PlasmidSample.generatePlasmidSample(myPlasmid, myStrain, container, vol, person);
            pls.changeName(this.sampleName.getText());
            pls.changeQuality(quality);
            pls.changeConcentration(conc);

            //set search tags if this is a gel-sample and/or frozen-stock
            if (this.jCheckBoxGelSample.isSelected())
            {
                pls.addSearchTag("gel-sample");
                pls.addSearchTag("enzyme1 "+this.jTextFieldEnzyme1.getText());
                pls.addSearchTag("enzyme2 "+this.jTextFieldEnzyme2.getText());
            }
            else
            {
                ArrayList<String>tag = pls.getSearchTags();
                for (int i = 0 ; i < tag.size(); i++)
                {
                    String s = tag.get(i);
                    if (s.startsWith("gel-sample")|| s.startsWith("enzyme1")|| s.startsWith("enzyme2"))
                        tag.remove(s);
                }

            }
            if (this.jCheckBoxisFrozenStock.isSelected())
            {
                pls.addSearchTag("frozen-stock");
            }
            else
            {
                ArrayList<String>tag = pls.getSearchTags();
                for (int i = 0 ; i < tag.size(); i++)
                {
                    String s = tag.get(i);
                    if (s.startsWith("frozen-stock"))
                    {
                        tag.remove(i);
                        break;
                    }

                }
            }

            //next check if user entered characterization data
            //if so, put xml file in database as an attachment
            // and update search tag
            if (this.jCheckBoxCharData.isSelected())
            {
                ArrayList<String>tag = pls.getSearchTags();
                tag.add("characterization-data");

            }

            pls.saveDefault();
        }
        String newContainerName = this.containerName.getText();
        String newBarcode = this.barcode.getText();

        boolean change =false;
        if (newContainerName !=null && newContainerName.length()> 0) {
            container.changeName(newContainerName);
            change =true;
        }
        if (newBarcode !=null && newBarcode.length() > 0) {
            container.changeBarcode(newBarcode);
            change =true;
        }
        if (change)
            container.saveDefault();


        this.setVisible(false);
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void jCheckBoxisFrozenStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxisFrozenStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxisFrozenStockActionPerformed

    private void jCheckBoxCharDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCharDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCharDataActionPerformed

    private void jButtonCharDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCharDataActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Characterization File");
        int returnVal =fileChooser.showOpenDialog(this);
                if (returnVal==JFileChooser.APPROVE_OPTION)
                {
                    File file =fileChooser.getSelectedFile();
                    CharDataXMLGenerator generator = new CharDataXMLGenerator(file);
                    xmlDataFile =  generator.generateXML();
                    //set search tag saying this sample has associated characterization data
                    if (xmlDataFile !=null)
                    {
                        this.jCheckBoxCharData.setSelected(true);

                    }
                    System.out.println("path = "+file.toString()+" \ndata file = "+file.getName());
                }
                else
                    System.out.println("Import file canceled by user");
    }//GEN-LAST:event_jButtonCharDataActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContainerEditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField concentrationText;
    private javax.swing.JTextField containerName;
    private javax.swing.JButton jButtonCharData;
    private javax.swing.JCheckBox jCheckBoxCharData;
    private javax.swing.JCheckBox jCheckBoxGelSample;
    private javax.swing.JCheckBox jCheckBoxisFrozenStock;
    private javax.swing.JComboBox jComboBoxPlasmid;
    private javax.swing.JComboBox jComboBoxStrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldEnzyme1;
    private javax.swing.JTextField jTextFieldEnzyme2;
    private javax.swing.JTextField qualityText;
    private javax.swing.JTextField sampleName;
    private javax.swing.JComboBox sampleTypeBox;
    private javax.swing.JButton save;
    private javax.swing.JTextField volumeText;
    // End of variables declaration//GEN-END:variables

    //my private variables
    private Plate myPlate;
    private Container selectedContainer;
    private File xmlDataFile;
    private static ArrayList<ObjLink> plasmidList = Collector.getAllLinksOf(ObjType.PLASMID);
    private static ArrayList<ObjLink> strainList = Collector.getAllLinksOf(ObjType.STRAIN);
}
