/*
 Copyright (c) 2009 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS..
 */

/*
 * hub.java
 *
 * Created on Mar 6, 2010, 5:00:34 PM
 */

package org.clothocad.tool.batterboard;

import java.io.File;
import java.lang.ref.WeakReference;
import java.util.ArrayList;
import org.clothocore.api.data.ObjLink;
import org.clothocore.api.data.ObjType;
import org.clothocore.api.data.Plate;
import org.clothocore.api.core.Collector;
import javax.swing.*;
import org.clothocore.api.data.PlateType;

/**
 *
 * @author J. Christopher Anderson
 */
public class plateChooser extends javax.swing.JFrame {

    /** Creates new form hub */
    public plateChooser() {
        super("Plate Chooser");
        plateHash = Collector.getAllLinksOf(ObjType.PLATE);
        allplatesUUIDs = plateHash.toArray();
        initComponents();
        setVisible(true);
        this.jButtonConfigDBActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barcodeField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        availablePlates = new javax.swing.JComboBox();
        newPlateButton = new javax.swing.JButton();
        newRack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jButtonConfigDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Enter plate  barcode:");

        submitButton.setText("view plate");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        availablePlates.setModel(new javax.swing.DefaultComboBoxModel(allplatesUUIDs));
        availablePlates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablePlatesActionPerformed(evt);
            }
        });

        newPlateButton.setText("Make New Plate");
        newPlateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlateButtonActionPerformed(evt);
            }
        });

        newRack.setText("Make New Rack");
        newRack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRackActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose plate/rack:");

        jButtonSearch.setText("Search..");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonConfigDB.setText("config DB");
        jButtonConfigDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(barcodeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(availablePlates, 0, 337, Short.MAX_VALUE)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(413, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPlateButton)
                        .addGap(32, 32, 32)
                        .addComponent(newRack)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonSearch)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonConfigDB)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(availablePlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlateButton)
                    .addComponent(newRack)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonConfigDB))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String uuid = barcodeField.getText();
        Plate aplate = Collector.getPlate( uuid);
        if(aplate==null) {
            return;
        }
        frame aframe = new frame( aplate);
        hub.guis.add(new WeakReference(aframe));
    }//GEN-LAST:event_submitButtonActionPerformed

    private void availablePlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablePlatesActionPerformed
        ObjLink link = (ObjLink) availablePlates.getSelectedItem();
        Plate aplate = Collector.getPlate( link.uuid);
        frame aframe = new frame( aplate);
        hub.guis.add(new WeakReference(aframe));
    }//GEN-LAST:event_availablePlatesActionPerformed

    private void newPlateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlateButtonActionPerformed
        // TODO add your handling code here:
       // System.out.println("batterboard:new plate clicked");
        ConfigurePlateFrame aframe =new ConfigurePlateFrame();
        hub.guis.add(new WeakReference(aframe));
        aframe.setVisible(true);
    }//GEN-LAST:event_newPlateButtonActionPerformed

    private void newRackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRackActionPerformed
        // TODO add your handling code here:
        //System.out.println("Batterboard: new rack clicked");
        ConfigureRackFrame aframe = new ConfigureRackFrame();
        hub.guis.add(new WeakReference(aframe));
        aframe.setVisible(true);
    }//GEN-LAST:event_newRackActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        searchForm aform = new searchForm();
        //JFrame aform = new JFrame();
        hub.guis.add(new WeakReference(aform));
       // aform.setVisible(true);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonConfigDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigDBActionPerformed
        // TODO add your handling code here:

      PlateType pcr_96 =  PlateType.retrieveByName("PCR_96");
      PlateType rack = PlateType.retrieveByName("RACK_9X9");

      if (pcr_96 ==null)
      {
          this.chooseFile(DbScript.picTypes.PCR_96);
      }

      if (rack ==null)
      {
          this.chooseFile(DbScript.picTypes.RACK_99);
      }

      if ( pcr_96!=null && rack !=null)
      {
          DbScript.setupExistingRack(rack);

          JOptionPane.showMessageDialog(this, "your DB is already configured with required PlateTypes");
          return;
      }

    else
      {
          JOptionPane.showConfirmDialog(this, "your DB is now configured with required plate types");
      }
        

    }//GEN-LAST:event_jButtonConfigDBActionPerformed


    private void chooseFile(DbScript.picTypes p)
    {
         JFileChooser fileChooser = new JFileChooser();
         String title = (p==DbScript.picTypes.PCR_96)? "Choose Pic for PCR 96" : "Choose Pic for Rack";
         fileChooser.setDialogTitle(title);
        int returnVal =fileChooser.showOpenDialog(this);
                if (returnVal==JFileChooser.APPROVE_OPTION)
                {
                    File file =fileChooser.getSelectedFile();
                    //set search tag saying this sample has associated characterization data
                    DbScript.setupDB(file, p);
                    System.out.println("path = "+file.toString()+" \ndata file = "+file.getName());
                }
                else
                    System.out.println("pic file canceled by user");
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new plateChooser();
            }
        });
    }

/**-----------------
     variables
 -----------------*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox availablePlates;
    private javax.swing.JTextField barcodeField;
    private javax.swing.JButton jButtonConfigDB;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newPlateButton;
    private javax.swing.JButton newRack;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
    private Object[] allplatesUUIDs;
    private ArrayList<ObjLink> plateHash;

}
