/*
 * 
Copyright (c) 2010 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */

/*
 * AddSampleDialog.java
 *
 * Created on Mar 5, 2011, 1:27:20 PM
 */

package org.clothocad.viewer.plateeditortc.guis;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.clothocore.api.core.Collector;
import org.clothocore.api.data.*;

/**
 *
 * @author jcanderson_Home
 */
public class AddSampleDialog extends javax.swing.JDialog {

    /** Creates new form AddSampleDialog */
    public AddSampleDialog(WellPanel aThis) {
        super(new JFrame(), false);
        initComponents();
        _myWell = aThis;
        authorField.setText(Collector.getCurrentUser().getName());
        typeChooserActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeChooser = new javax.swing.JComboBox();
        typeLabel = new javax.swing.JLabel();
        primaryField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        volumeField = new javax.swing.JTextField();
        secondaryLabel = new javax.swing.JLabel();
        secondaryField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.jLabel1.text")); // NOI18N

        typeChooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plasmid Sample", "Oligo Sample", "Strain Sample" }));
        typeChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeChooserActionPerformed(evt);
            }
        });

        typeLabel.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.typeLabel.text")); // NOI18N

        primaryField.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.primaryField.text")); // NOI18N

        createBtn.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.createBtn.text")); // NOI18N
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.cancelBtn.text")); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.jLabel3.text")); // NOI18N

        authorField.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.authorField.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.jLabel4.text")); // NOI18N

        volumeField.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.volumeField.text")); // NOI18N

        secondaryLabel.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.secondaryLabel.text")); // NOI18N

        secondaryField.setText(org.openide.util.NbBundle.getMessage(AddSampleDialog.class, "AddSampleDialog.secondaryField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(typeLabel)
                            .addComponent(secondaryLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(primaryField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(typeChooser, 0, 172, Short.MAX_VALUE)
                            .addComponent(volumeField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(secondaryField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(primaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondaryLabel)
                    .addComponent(secondaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn)
                    .addComponent(cancelBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeChooserActionPerformed
        switch(typeChooser.getSelectedIndex()) {
            case 0:
                typeLabel.setText("Plasmid");
                secondaryLabel.setVisible(true);
                secondaryField.setVisible(true);
                break;
            case 1:
                typeLabel.setText("Oligo");
                secondaryLabel.setVisible(false);
                secondaryField.setVisible(false);
                break;
            case 2:
                typeLabel.setText("Strain");
                secondaryLabel.setVisible(false);
                secondaryField.setVisible(false);
                break;
            default:
                return;
        }
    }//GEN-LAST:event_typeChooserActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        switch(typeChooser.getSelectedIndex()) {
            case 0:
                createPlasmidSample();
                break;
            case 1:
                createOligoSample();
                break;
            case 2:
                createStrainSample();
                break;
            default:
                return;
        }



    }//GEN-LAST:event_createBtnActionPerformed
    
    private void createPlasmidSample() {
        String plasmidName = primaryField.getText();
        String strainName = secondaryField.getText();
        String authorName = authorField.getText();
        String volume = volumeField.getText();
        String type = (String) typeChooser.getSelectedItem();
        setVisible(false);

        //Get the Plasmid
        Plasmid aplas = Plasmid.retrieveByName(plasmidName);
        if(aplas==null) {
            JOptionPane.showMessageDialog(null, "The Plasmid you entered does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Get the Strain
        Strain astrain = Strain.retrieveByName(strainName);
        if(astrain==null) {
            JOptionPane.showMessageDialog(null, "The Strain you entered does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Set other information
        Double vol;
        try {
            vol = Double.parseDouble(volume);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "You didn't put a real number in for the volume", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Person auth = Person.retrieveByName(authorName);
        if(auth==null) {
            JOptionPane.showMessageDialog(null, "Your author does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Create the Sample
        Sample asam = PlasmidSample.generatePlasmidSample( aplas, astrain, _myWell._con, vol, auth);
        if(asam==null) {
            JOptionPane.showMessageDialog(null, "Something went wrong with creating your sample", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        _myWell._sam = asam;
        _myWell.preinit();
        _myWell._con.saveDefault();
    }

    private void createOligoSample() {
        String oligoName = primaryField.getText();
        String authorName = authorField.getText();
        String volume = volumeField.getText();
        String type = (String) typeChooser.getSelectedItem();
        setVisible(false);

        //Fetch the Oligo
        Oligo anoligo = Oligo.retrieveByName(oligoName);
        if(anoligo==null) {
            JOptionPane.showMessageDialog(null, "The Oligo you entered does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Set other information
        Double vol;
        try {
            vol = Double.parseDouble(volume);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "You didn't put a real number in for the volume", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Person auth = Person.retrieveByName(authorName);
        if(auth==null) {
            JOptionPane.showMessageDialog(null, "Your author does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Create the sample
        Sample asam = OligoSample.generateOligoSample( anoligo, _myWell._con, vol, auth );
        if(asam==null) {
            JOptionPane.showMessageDialog(null, "Something went wrong with creating your sample", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        _myWell._sam = asam;
        _myWell.preinit();
        _myWell._con.saveDefault();
    }

    private void createStrainSample() {
        String strainName = primaryField.getText();
        String authorName = authorField.getText();
        String volume = volumeField.getText();
        String type = (String) typeChooser.getSelectedItem();
        setVisible(false);

        //Get the Strain
        Strain astrain = Strain.retrieveByName(strainName);
        if(astrain==null) {
            JOptionPane.showMessageDialog(null, "The Strain you entered does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Set other information
        Double vol;
        try {
            vol = Double.parseDouble(volume);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "You didn't put a real number in for the volume", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Person auth = Person.retrieveByName(authorName);
        if(auth==null) {
            JOptionPane.showMessageDialog(null, "Your author does not exist", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Create the Sample
        Sample asam = StrainSample.generateStrainSample(astrain, _myWell._con, vol, auth);
        if(asam==null) {
            JOptionPane.showMessageDialog(null, "Something went wrong with creating your sample", "Sample Creation Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }

        _myWell._sam = asam;
        _myWell.preinit();
        _myWell._con.saveDefault();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField primaryField;
    private javax.swing.JTextField secondaryField;
    private javax.swing.JLabel secondaryLabel;
    private javax.swing.JComboBox typeChooser;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField volumeField;
    // End of variables declaration//GEN-END:variables

    private WellPanel _myWell;
}
