/*
 * sequenceViewPartExport.java
 *
 * Created on July 7, 2008, 11:40 AM
 */

/*
 Copyright (c) 2008 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS..
 */

package org.clothocad.tool.sequenceview;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import org.clothocore.util.dialog.ClothoDialogBox;
//import org.clothocad.util.ClothoDialogBox;

/**
 *
 * @author  Douglas Densmore
 */
public class SequenceViewPartExport extends javax.swing.JFrame {

    /** Creates new form sequenceViewPartExport */
    public SequenceViewPartExport() {
        initComponents();
    }
    
        /** Creates new form sequenceViewPartExport */
    public SequenceViewPartExport(SequenceView sv) {
        initComponents();
        _sv = sv;
        addWindowListener(new WindowAdapter(){
        @Override
        public void windowClosing(WindowEvent we){
            ClothoDialogBox db = new ClothoDialogBox("Clotho: Exit Check", "Are you sure you want to close the packager?");
        
            if(db.show_optionDialog(javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION)
                dispose();
            }
        });
    }

    public String getBeginIndex()
    {
        return fromTextField.getText();
    }
    
    public javax.swing.JTextPane getDataPane()
    {
        return dataTextPane;
    }
    
    public String getEndIndex()
    {
      return toTextField.getText(); 
    }
    
    public javax.swing.JComboBox getFields()
    {
        
       return fieldComboBox;
    }
    
    public javax.swing.JComboBox getLibraries()
    {
        
       return libraryComboBox;
    }
    
    public boolean highlightSeqSel()
    {
        return ssRadioButton.isSelected();
    }
    
    public boolean intervalSeqSel()
    {
        return intervalRadioButton.isSelected();
    }
    
    public void setVisibleFlag(boolean b)
    {
        _visible = b;
    }
    public boolean visible()
    {
        return _visible;
    }
   
    /*
    public int getImportButtonSelection()
    {
        return importbuttonGroup.
    }*/
    
    public boolean wholeSeqSel()
    {
        return wsRadioButton.isSelected();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importbuttonGroup = new javax.swing.ButtonGroup();
        libraryComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTextPane = new javax.swing.JTextPane();
        fieldComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iconPathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        packageButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        wsRadioButton = new javax.swing.JRadioButton();
        ssRadioButton = new javax.swing.JRadioButton();
        intervalRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clotho: Part Packager");
        setIconImage(new ImageIcon("data/icons/ClothoIcon.png").getImage());

        libraryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        libraryComboBox.setToolTipText("Which connection should the part be associated with?");
        libraryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Connection");

        dataTextPane.setToolTipText("Data to package as a part");
        jScrollPane1.setViewportView(dataTextPane);

        fieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fieldComboBox.setToolTipText("Which field should the data represent in the new part?");

        jLabel2.setText("Assign Data as");

        jLabel3.setText("Data to Package");

        fromTextField.setToolTipText("Starting interval of the sequence data to import");

        toTextField.setToolTipText("End interval of the sequence data to import");

        jLabel4.setText("From");

        jLabel5.setText("To");

        iconPathTextField.setToolTipText("Path for the image to associate with the part");

        browseButton.setText("Browse");
        browseButton.setToolTipText("Set the icon image path");

        jLabel6.setText("Icon Image Path");

        packageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/packagePartIcon.png"))); // NOI18N
        packageButton.setToolTipText("Package the part for the selected connection and data");
        packageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.setToolTipText("Import data to package as a part");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        importbuttonGroup.add(wsRadioButton);
        wsRadioButton.setText("Whole Sequence");
        wsRadioButton.setToolTipText("Import the whole sequence");

        importbuttonGroup.add(ssRadioButton);
        ssRadioButton.setText("Selected Sequence");
        ssRadioButton.setToolTipText("Import the selected sequence");

        importbuttonGroup.add(intervalRadioButton);
        intervalRadioButton.setText("Interval");
        intervalRadioButton.setToolTipText("Import the provided interval");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wsRadioButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ssRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(importButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(intervalRadioButton)
                            .addComponent(libraryComboBox, 0, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(browseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                                .addComponent(packageButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(libraryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wsRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssRadioButton)
                            .addComponent(importButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intervalRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(iconPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton))
                    .addComponent(packageButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void libraryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryComboBoxActionPerformed
   _sv.updateFields(this);
}//GEN-LAST:event_libraryComboBoxActionPerformed

private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
    _sv.importData(this);
}//GEN-LAST:event_importButtonActionPerformed

private void packageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageButtonActionPerformed
    _sv.packageData(this);
}//GEN-LAST:event_packageButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SequenceViewPartExport().setVisible(true);
            }
        });
    }

    private SequenceView _sv;
    private boolean _visible;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JTextPane dataTextPane;
    private javax.swing.JComboBox fieldComboBox;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField iconPathTextField;
    private javax.swing.JButton importButton;
    private javax.swing.ButtonGroup importbuttonGroup;
    private javax.swing.JRadioButton intervalRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox libraryComboBox;
    private javax.swing.JButton packageButton;
    private javax.swing.JRadioButton ssRadioButton;
    private javax.swing.JTextField toTextField;
    private javax.swing.JRadioButton wsRadioButton;
    // End of variables declaration//GEN-END:variables

}
