/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 Copyright (c) 2008 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS..
 */

package org.clothocad.tool.sequenceview;

import java.io.File;
import javax.swing.ImageIcon;
import org.clothocore.util.chooser.ClothoOpenChooser;
//import org.clothocad.util.ClothoOpenChooser;

/**
 *
 * @author Douglas Densmore
 */
public class SequenceViewPreferences extends javax.swing.JFrame {

    /** Creates new form SequenceViewPreferences */
    public SequenceViewPreferences() {
        initComponents();
    }

    public SequenceViewPreferences(SequenceView sv) {
        
        initComponents();
        pathTextField.setText(_openChooser.getCurrentDirectory().toString());
        _sv = sv;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        circularCheckBox = new javax.swing.JCheckBox();
        methylateCheckBox = new javax.swing.JCheckBox();
        degenCheckBox = new javax.swing.JCheckBox();
        codonCheckBox = new javax.swing.JCheckBox();
        nucLabel = new javax.swing.JLabel();
        dnaRadioButton = new javax.swing.JRadioButton();
        rnaRadioButton = new javax.swing.JRadioButton();
        proteinLabel = new javax.swing.JLabel();
        oneLetterRadioButton = new javax.swing.JRadioButton();
        threeLetterRadioButton = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JToggleButton();
        pathLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.title")); // NOI18N
        setIconImage(new ImageIcon("data/icons/ClothoIcon.png").getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.jPanel1.border.title"))); // NOI18N
        jPanel1.setToolTipText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.jPanel1.toolTipText")); // NOI18N

        methylateCheckBox.setText("Methylate (Dcm/Dam) by default");

        degenCheckBox.setText("Allow degeneracy by default");

        codonCheckBox.setText("Use multiple start codons");

        nucLabel.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.nucLabel.text")); // NOI18N

        buttonGroup1.add(dnaRadioButton);
        dnaRadioButton.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.dnaRadioButton.text")); // NOI18N

        buttonGroup1.add(rnaRadioButton);
        rnaRadioButton.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.rnaRadioButton.text")); // NOI18N

        proteinLabel.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.proteinLabel.text")); // NOI18N

        buttonGroup2.add(oneLetterRadioButton);
        oneLetterRadioButton.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.oneLetterRadioButton.text")); // NOI18N

        buttonGroup2.add(threeLetterRadioButton);
        threeLetterRadioButton.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.threeLetterRadioButton.text")); // NOI18N

        saveButton.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.saveButton.text")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        pathLabel.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.pathLabel.text")); // NOI18N

        pathTextField.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.pathTextField.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nucLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rnaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proteinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneLetterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threeLetterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(circularCheckBox)
                .addGap(6, 6, 6)
                .addComponent(methylateCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codonCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degenCheckBox))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathLabel)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circularCheckBox)
                    .addComponent(methylateCheckBox)
                    .addComponent(degenCheckBox)
                    .addComponent(codonCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nucLabel)
                    .addComponent(dnaRadioButton)
                    .addComponent(rnaRadioButton)
                    .addComponent(proteinLabel)
                    .addComponent(oneLetterRadioButton)
                    .addComponent(threeLetterRadioButton)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SequenceViewPreferences.class, "SequenceViewPreferences.jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        _sv.savePrefernces();
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (!_openChooserInit) {
            _openChooser = new ClothoOpenChooser("Clotho: Preferences Open File Chooser");
            _openChooserInit = true;
        }
        _openChooser.setTitle("Clotho Preferences: Sequence View File Path Selection");
        _openChooser.open_Window();
        File f = _openChooser.getFile();
        if(!f.toString().equals("")) {
            pathTextField.setText(f.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean getCircular()
    {
        return circularCheckBox.isSelected();
    }

    public void setCircular(boolean b)
    {
        circularCheckBox.setSelected(b);
    }

    public boolean getDegen()
    {
        return degenCheckBox.isSelected();
    }

    public void setDegen(boolean b)
    {
        degenCheckBox.setSelected(b);
    }

    public boolean getDNA()
    {
        return dnaRadioButton.isSelected();
    }

    public void setDNA(boolean b)
    {
        dnaRadioButton.setSelected(b);
    }

    public String getFilePath()
    {
        return pathTextField.getText();
    }

    public void setFilePath (String s)
    {
        pathTextField.setText(s);
    }

    public boolean getMethylated()
    {
        return methylateCheckBox.isSelected();
    }

    public void setMethylated(boolean b)
    {
        methylateCheckBox.setSelected(b);
    }

    public boolean getMultiCodons()
    {
        return codonCheckBox.isSelected();
    }

    public void setMultiCodons(boolean b)
    {
        codonCheckBox.setSelected(b);
    }

    public boolean getThreeLetterCode()
    {
        return threeLetterRadioButton.isSelected();
    }

    public void setThreeLetterCode(boolean b)
    {
        threeLetterRadioButton.setSelected(b);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SequenceViewPreferences().setVisible(true);
            }
        });
    }

    private SequenceView _sv;
    private boolean _openChooserInit;
    private ClothoOpenChooser _openChooser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox circularCheckBox;
    private javax.swing.JCheckBox codonCheckBox;
    private javax.swing.JCheckBox degenCheckBox;
    private javax.swing.JRadioButton dnaRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox methylateCheckBox;
    private javax.swing.JLabel nucLabel;
    private javax.swing.JRadioButton oneLetterRadioButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JRadioButton rnaRadioButton;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JRadioButton threeLetterRadioButton;
    // End of variables declaration//GEN-END:variables

}
