/*
 * 
Copyright (c) 2010 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */

/*
 * PlasmidSamplePanel.java
 *
 * Created on Mar 4, 2011, 8:33:43 PM
 */
package org.clothocad.viewer.sampleeditortc.guis;

import org.clothocore.api.data.Plasmid;
import org.clothocore.api.data.PlasmidSample;
import org.clothocore.api.data.Person;
import org.clothocore.api.data.Strain;

/**
 *
 * @author jcanderson_Home
 */
public class PlasmidSamplePanel extends javax.swing.JPanel {

    public PlasmidSamplePanel(PlasmidSample plasmidSample) {
        initComponents();
        _sample = plasmidSample;
        setData();
    }

    private void setData() {
        int quality = _sample.getQuality();
        QualityCombo.setSelectedIndex(quality);

        sampleNameField.setText((_sample.getName()));
        authorNameField.setText(_sample.getAuthor().getName());
        volField.setText(Double.toString(_sample.getVolume()));

        Plasmid plasmid = _sample.getPlasmid();
        Strain strain = _sample.getSourceStrain();

        strainField.setText(strain.getName());
        plasmidField.setText(plasmid.getName());
        formatField.setText(plasmid.getFormat().getName());

        plateField.setText(_sample.getPlate().toString());
        wellField.setText(_sample.getContainer().getWell());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sampleNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        authorNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        plasmidField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        formatField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        strainField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        QualityCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        launchOligo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        volField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        plateField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        wellField = new javax.swing.JTextField();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel1.text_1")); // NOI18N

        sampleNameField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.sampleNameField.text_1")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel2.text_1")); // NOI18N

        authorNameField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.authorNameField.text_1")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel3.text_1")); // NOI18N

        plasmidField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.plasmidField.text_1")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel4.text_1")); // NOI18N

        formatField.setEditable(false);
        formatField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.formatField.text_1")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel5.text_1")); // NOI18N

        strainField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.strainField.text_1")); // NOI18N

        saveBtn.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.saveBtn.text_1")); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.cancelBtn.text_1")); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        QualityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fails", "Unknown", "Caution", "Works", "Sequenced" }));
        QualityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualityComboActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel6.text_1")); // NOI18N

        launchOligo.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.launchOligo.text_1")); // NOI18N
        launchOligo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchOligoActionPerformed(evt);
            }
        });

        jLabel7.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel7.text_1")); // NOI18N

        volField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.volField.text_1")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel8.text_1")); // NOI18N

        plateField.setEditable(false);
        plateField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.plateField.text_1")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.jLabel9.text")); // NOI18N

        wellField.setEditable(false);
        wellField.setText(org.openide.util.NbBundle.getMessage(PlasmidSamplePanel.class, "PlasmidSamplePanel.wellField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(sampleNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plateField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wellField, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(volField, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plasmidField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(strainField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(formatField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(launchOligo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn)
                        .addContainerGap())
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sampleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(authorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(QualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(wellField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(plasmidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn)
                    .addComponent(launchOligo))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QualityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QualityComboActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setData();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        short quality = (short) QualityCombo.getSelectedIndex();
        _sample.changeQuality(quality);
        _sample.changeName(sampleNameField.getText());
        Person author = Person.retrieveByName(authorNameField.getText());
        if (author != null) {
            _sample.changeAuthor(author);
        }

        try {
            String svol = volField.getText();
            Double adub = Double.parseDouble(svol);
            _sample.changeVolume(adub);
        } catch (Exception e) {
        }

        Plasmid plasmid = Plasmid.retrieveByName(plasmidField.getText());
        if (plasmid != null) {
            _sample.changePlasmid(plasmid);
        }

        Strain strain = Strain.retrieveByName(strainField.getText());
        if (strain != null) {
            _sample.changeSourceStrain(strain);
        }

        setData();
        _sample.saveDefault();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void launchOligoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchOligoActionPerformed
        _sample.getPlasmid().launchDefaultViewer();
    }//GEN-LAST:event_launchOligoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox QualityCombo;
    private javax.swing.JTextField authorNameField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField formatField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton launchOligo;
    private javax.swing.JTextField plasmidField;
    private javax.swing.JTextField plateField;
    private javax.swing.JTextField sampleNameField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField strainField;
    private javax.swing.JTextField volField;
    private javax.swing.JTextField wellField;
    // End of variables declaration//GEN-END:variables
    PlasmidSample _sample;
}
