/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MakeObjectFrame.java
 *
 * Created on Aug 28, 2011, 8:55:31 AM
 */
package org.clothocore.widget.fabdash;

import java.util.ArrayList;
import org.clothocore.api.core.Collector;
import org.clothocore.api.data.ObjLink;
import org.clothocore.api.data.ObjType;
import org.clothocore.api.data.Sample.SampleType;

/**
 *
 * @author Henry
 */
public class MakeObjectFrame extends javax.swing.JFrame {

    /** Creates new form MakeObjectFrame */
    public MakeObjectFrame() {
        initComponents();
    }

    public MakeObjectFrame(ObjType o) {

        initComponents();
        this.setTitle("Create new Clotho " + o);
        collectionComboBox.removeAllItems();
        ArrayList<ObjLink> allLinksOf = Collector.getAllLinksOf(ObjType.COLLECTION);
        for (ObjLink oj : allLinksOf) {
            collectionComboBox.addItem(oj.name);
        }
        saveType = o;
        if (saveType.equals(ObjType.PART)) {
            swapPanel.remove(volumeLabel);
            swapPanel.remove(volumeField);
            swapPanel.remove(cdsCheckBox);
            formatComboBox.removeAllItems();
            ArrayList<ObjLink> formatLinks = Collector.getAllLinksOf(ObjType.FORMAT);
            for (ObjLink ol : formatLinks) {
                formatComboBox.addItem(ol.name);
            }
        } else if (saveType.equals(ObjType.OLIGO)) {
            swapPanel.remove(volumeLabel);
            swapPanel.remove(volumeField);
            swapPanel.remove(cdsCheckBox);
            swapPanel.remove(formatLabel);
            swapPanel.remove(formatComboBox);
        } else if (saveType.equals(ObjType.VECTOR)) {
            swapPanel.remove(volumeLabel);
            swapPanel.remove(volumeField);
            swapPanel.remove(cdsCheckBox);
            formatComboBox.removeAllItems();
            ArrayList<ObjLink> formatLinks = Collector.getAllLinksOf(ObjType.FORMAT);
            for (ObjLink ol : formatLinks) {
                formatComboBox.addItem(ol.name);
            }

        } else if (saveType.equals(ObjType.FEATURE)) {
            swapPanel.remove(volumeLabel);
            swapPanel.remove(volumeField);

            swapPanel.remove(formatLabel);
            swapPanel.remove(formatComboBox);
        } else if (saveType.equals(ObjType.SAMPLE)) {
            swapPanel.remove(cdsCheckBox);
            swapPanel.remove(sequenceLabel);
            swapPanel.remove(jScrollPane2);
            formatComboBox.removeAllItems();
            for (SampleType st : SampleType.values()) {
                formatComboBox.addItem(st.toString());
            }
            formatLabel.setText("Type");
        } else if (saveType.equals(ObjType.COLLECTION)) {
            swapPanel.remove(volumeLabel);
            swapPanel.remove(volumeField);
            swapPanel.remove(cdsCheckBox);
            swapPanel.remove(sequenceLabel);
            swapPanel.remove(jScrollPane2);
            swapPanel.remove(formatLabel);
            swapPanel.remove(formatComboBox);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        swapPanel = new javax.swing.JPanel();
        sequenceLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        formatComboBox = new javax.swing.JComboBox();
        formatLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        volumeField = new javax.swing.JTextField();
        cdsCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        collectionComboBox = new javax.swing.JComboBox();
        statusLabel = new javax.swing.JLabel();

        jLabel2.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.jLabel2.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setMaximumSize(new java.awt.Dimension(260, 300));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(260, 300));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.jTextField1.text")); // NOI18N
        jTextField1.setToolTipText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.jTextField1.toolTipText")); // NOI18N

        saveButton.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.saveButton.text")); // NOI18N
        saveButton.setMaximumSize(new java.awt.Dimension(65, 23));
        saveButton.setMinimumSize(new java.awt.Dimension(65, 23));
        saveButton.setPreferredSize(new java.awt.Dimension(65, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        swapPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sequenceLabel.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.sequenceLabel.text")); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        formatLabel.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.formatLabel.text")); // NOI18N

        volumeLabel.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.volumeLabel.text")); // NOI18N

        volumeField.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.volumeField.text")); // NOI18N

        cdsCheckBox.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.cdsCheckBox.text")); // NOI18N

        javax.swing.GroupLayout swapPanelLayout = new javax.swing.GroupLayout(swapPanel);
        swapPanel.setLayout(swapPanelLayout);
        swapPanelLayout.setHorizontalGroup(
            swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(swapPanelLayout.createSequentialGroup()
                .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdsCheckBox)
                    .addGroup(swapPanelLayout.createSequentialGroup()
                        .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sequenceLabel)
                            .addComponent(formatLabel)
                            .addComponent(volumeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(formatComboBox, 0, 188, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addContainerGap())
        );

        swapPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {formatLabel, sequenceLabel, volumeLabel});

        swapPanelLayout.setVerticalGroup(
            swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(swapPanelLayout.createSequentialGroup()
                .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sequenceLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatLabel)
                    .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(swapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeLabel)
                    .addComponent(volumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cdsCheckBox))
        );

        jLabel3.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.jLabel3.text")); // NOI18N

        collectionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        collectionComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.collectionComboBox.toolTipText")); // NOI18N
        collectionComboBox.setMaximumSize(new java.awt.Dimension(186, 20));
        collectionComboBox.setMinimumSize(new java.awt.Dimension(186, 20));
        collectionComboBox.setPreferredSize(new java.awt.Dimension(186, 20));

        statusLabel.setText(org.openide.util.NbBundle.getMessage(MakeObjectFrame.class, "MakeObjectFrame.statusLabel.text")); // NOI18N
        statusLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusLabel.setMaximumSize(new java.awt.Dimension(240, 18));
        statusLabel.setMinimumSize(new java.awt.Dimension(240, 18));
        statusLabel.setPreferredSize(new java.awt.Dimension(240, 18));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(swapPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(collectionComboBox, 0, 186, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        backgroundPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, saveButton});

        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(collectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(swapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        backgroundPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelButton, saveButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
}//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeObjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeObjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeObjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeObjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MakeObjectFrame().setVisible(true);
            }
        });
    }
    private ObjType saveType;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox cdsCheckBox;
    private javax.swing.JComboBox collectionComboBox;
    private javax.swing.JComboBox formatComboBox;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sequenceLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel swapPanel;
    private javax.swing.JTextField volumeField;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
